# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _libgeoda
else:
    import _libgeoda

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libgeoda.delete_SwigPyIterator

    def value(self):
        return _libgeoda.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _libgeoda.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _libgeoda.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _libgeoda.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _libgeoda.SwigPyIterator_equal(self, x)

    def copy(self):
        return _libgeoda.SwigPyIterator_copy(self)

    def next(self):
        return _libgeoda.SwigPyIterator_next(self)

    def __next__(self):
        return _libgeoda.SwigPyIterator___next__(self)

    def previous(self):
        return _libgeoda.SwigPyIterator_previous(self)

    def advance(self, n):
        return _libgeoda.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _libgeoda.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _libgeoda.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _libgeoda.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _libgeoda.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _libgeoda.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _libgeoda.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _libgeoda:
_libgeoda.SwigPyIterator_swigregister(SwigPyIterator)

class VecVoid(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecVoid_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecVoid___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecVoid___bool__(self)

    def __len__(self):
        return _libgeoda.VecVoid___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecVoid___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecVoid___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecVoid___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecVoid___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecVoid___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecVoid___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecVoid_pop(self)

    def append(self, x):
        return _libgeoda.VecVoid_append(self, x)

    def empty(self):
        return _libgeoda.VecVoid_empty(self)

    def size(self):
        return _libgeoda.VecVoid_size(self)

    def swap(self, v):
        return _libgeoda.VecVoid_swap(self, v)

    def begin(self):
        return _libgeoda.VecVoid_begin(self)

    def end(self):
        return _libgeoda.VecVoid_end(self)

    def rbegin(self):
        return _libgeoda.VecVoid_rbegin(self)

    def rend(self):
        return _libgeoda.VecVoid_rend(self)

    def clear(self):
        return _libgeoda.VecVoid_clear(self)

    def get_allocator(self):
        return _libgeoda.VecVoid_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecVoid_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecVoid_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecVoid_swiginit(self, _libgeoda.new_VecVoid(*args))

    def push_back(self, x):
        return _libgeoda.VecVoid_push_back(self, x)

    def front(self):
        return _libgeoda.VecVoid_front(self)

    def back(self):
        return _libgeoda.VecVoid_back(self)

    def assign(self, n, x):
        return _libgeoda.VecVoid_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecVoid_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecVoid_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecVoid_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecVoid_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecVoid

# Register VecVoid in _libgeoda:
_libgeoda.VecVoid_swigregister(VecVoid)

class VecFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecFloat___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecFloat___bool__(self)

    def __len__(self):
        return _libgeoda.VecFloat___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecFloat___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecFloat_pop(self)

    def append(self, x):
        return _libgeoda.VecFloat_append(self, x)

    def empty(self):
        return _libgeoda.VecFloat_empty(self)

    def size(self):
        return _libgeoda.VecFloat_size(self)

    def swap(self, v):
        return _libgeoda.VecFloat_swap(self, v)

    def begin(self):
        return _libgeoda.VecFloat_begin(self)

    def end(self):
        return _libgeoda.VecFloat_end(self)

    def rbegin(self):
        return _libgeoda.VecFloat_rbegin(self)

    def rend(self):
        return _libgeoda.VecFloat_rend(self)

    def clear(self):
        return _libgeoda.VecFloat_clear(self)

    def get_allocator(self):
        return _libgeoda.VecFloat_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecFloat_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecFloat_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecFloat_swiginit(self, _libgeoda.new_VecFloat(*args))

    def push_back(self, x):
        return _libgeoda.VecFloat_push_back(self, x)

    def front(self):
        return _libgeoda.VecFloat_front(self)

    def back(self):
        return _libgeoda.VecFloat_back(self)

    def assign(self, n, x):
        return _libgeoda.VecFloat_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecFloat_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecFloat_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecFloat_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecFloat_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecFloat

# Register VecFloat in _libgeoda:
_libgeoda.VecFloat_swigregister(VecFloat)

class VecString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecString___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecString___bool__(self)

    def __len__(self):
        return _libgeoda.VecString___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecString___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecString___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecString___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecString___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecString___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecString___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecString_pop(self)

    def append(self, x):
        return _libgeoda.VecString_append(self, x)

    def empty(self):
        return _libgeoda.VecString_empty(self)

    def size(self):
        return _libgeoda.VecString_size(self)

    def swap(self, v):
        return _libgeoda.VecString_swap(self, v)

    def begin(self):
        return _libgeoda.VecString_begin(self)

    def end(self):
        return _libgeoda.VecString_end(self)

    def rbegin(self):
        return _libgeoda.VecString_rbegin(self)

    def rend(self):
        return _libgeoda.VecString_rend(self)

    def clear(self):
        return _libgeoda.VecString_clear(self)

    def get_allocator(self):
        return _libgeoda.VecString_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecString_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecString_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecString_swiginit(self, _libgeoda.new_VecString(*args))

    def push_back(self, x):
        return _libgeoda.VecString_push_back(self, x)

    def front(self):
        return _libgeoda.VecString_front(self)

    def back(self):
        return _libgeoda.VecString_back(self)

    def assign(self, n, x):
        return _libgeoda.VecString_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecString_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecString_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecString_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecString_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecString

# Register VecString in _libgeoda:
_libgeoda.VecString_swigregister(VecString)

class VecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecDouble___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecDouble___bool__(self)

    def __len__(self):
        return _libgeoda.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecDouble___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecDouble_pop(self)

    def append(self, x):
        return _libgeoda.VecDouble_append(self, x)

    def empty(self):
        return _libgeoda.VecDouble_empty(self)

    def size(self):
        return _libgeoda.VecDouble_size(self)

    def swap(self, v):
        return _libgeoda.VecDouble_swap(self, v)

    def begin(self):
        return _libgeoda.VecDouble_begin(self)

    def end(self):
        return _libgeoda.VecDouble_end(self)

    def rbegin(self):
        return _libgeoda.VecDouble_rbegin(self)

    def rend(self):
        return _libgeoda.VecDouble_rend(self)

    def clear(self):
        return _libgeoda.VecDouble_clear(self)

    def get_allocator(self):
        return _libgeoda.VecDouble_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecDouble_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecDouble_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecDouble_swiginit(self, _libgeoda.new_VecDouble(*args))

    def push_back(self, x):
        return _libgeoda.VecDouble_push_back(self, x)

    def front(self):
        return _libgeoda.VecDouble_front(self)

    def back(self):
        return _libgeoda.VecDouble_back(self)

    def assign(self, n, x):
        return _libgeoda.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecDouble_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecDouble_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecDouble

# Register VecDouble in _libgeoda:
_libgeoda.VecDouble_swigregister(VecDouble)

class VecChar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecChar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecChar___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecChar___bool__(self)

    def __len__(self):
        return _libgeoda.VecChar___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecChar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecChar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecChar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecChar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecChar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecChar___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecChar_pop(self)

    def append(self, x):
        return _libgeoda.VecChar_append(self, x)

    def empty(self):
        return _libgeoda.VecChar_empty(self)

    def size(self):
        return _libgeoda.VecChar_size(self)

    def swap(self, v):
        return _libgeoda.VecChar_swap(self, v)

    def begin(self):
        return _libgeoda.VecChar_begin(self)

    def end(self):
        return _libgeoda.VecChar_end(self)

    def rbegin(self):
        return _libgeoda.VecChar_rbegin(self)

    def rend(self):
        return _libgeoda.VecChar_rend(self)

    def clear(self):
        return _libgeoda.VecChar_clear(self)

    def get_allocator(self):
        return _libgeoda.VecChar_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecChar_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecChar_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecChar_swiginit(self, _libgeoda.new_VecChar(*args))

    def push_back(self, x):
        return _libgeoda.VecChar_push_back(self, x)

    def front(self):
        return _libgeoda.VecChar_front(self)

    def back(self):
        return _libgeoda.VecChar_back(self)

    def assign(self, n, x):
        return _libgeoda.VecChar_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecChar_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecChar_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecChar_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecChar_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecChar

# Register VecChar in _libgeoda:
_libgeoda.VecChar_swigregister(VecChar)

class VecVecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecVecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecVecDouble___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecVecDouble___bool__(self)

    def __len__(self):
        return _libgeoda.VecVecDouble___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecVecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecVecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecVecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecVecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecVecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecVecDouble___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecVecDouble_pop(self)

    def append(self, x):
        return _libgeoda.VecVecDouble_append(self, x)

    def empty(self):
        return _libgeoda.VecVecDouble_empty(self)

    def size(self):
        return _libgeoda.VecVecDouble_size(self)

    def swap(self, v):
        return _libgeoda.VecVecDouble_swap(self, v)

    def begin(self):
        return _libgeoda.VecVecDouble_begin(self)

    def end(self):
        return _libgeoda.VecVecDouble_end(self)

    def rbegin(self):
        return _libgeoda.VecVecDouble_rbegin(self)

    def rend(self):
        return _libgeoda.VecVecDouble_rend(self)

    def clear(self):
        return _libgeoda.VecVecDouble_clear(self)

    def get_allocator(self):
        return _libgeoda.VecVecDouble_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecVecDouble_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecVecDouble_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecVecDouble_swiginit(self, _libgeoda.new_VecVecDouble(*args))

    def push_back(self, x):
        return _libgeoda.VecVecDouble_push_back(self, x)

    def front(self):
        return _libgeoda.VecVecDouble_front(self)

    def back(self):
        return _libgeoda.VecVecDouble_back(self)

    def assign(self, n, x):
        return _libgeoda.VecVecDouble_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecVecDouble_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecVecDouble_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecVecDouble_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecVecDouble_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecVecDouble

# Register VecVecDouble in _libgeoda:
_libgeoda.VecVecDouble_swigregister(VecVecDouble)

class VecInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecInt___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecInt___bool__(self)

    def __len__(self):
        return _libgeoda.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecInt___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecInt_pop(self)

    def append(self, x):
        return _libgeoda.VecInt_append(self, x)

    def empty(self):
        return _libgeoda.VecInt_empty(self)

    def size(self):
        return _libgeoda.VecInt_size(self)

    def swap(self, v):
        return _libgeoda.VecInt_swap(self, v)

    def begin(self):
        return _libgeoda.VecInt_begin(self)

    def end(self):
        return _libgeoda.VecInt_end(self)

    def rbegin(self):
        return _libgeoda.VecInt_rbegin(self)

    def rend(self):
        return _libgeoda.VecInt_rend(self)

    def clear(self):
        return _libgeoda.VecInt_clear(self)

    def get_allocator(self):
        return _libgeoda.VecInt_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecInt_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecInt_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecInt_swiginit(self, _libgeoda.new_VecInt(*args))

    def push_back(self, x):
        return _libgeoda.VecInt_push_back(self, x)

    def front(self):
        return _libgeoda.VecInt_front(self)

    def back(self):
        return _libgeoda.VecInt_back(self)

    def assign(self, n, x):
        return _libgeoda.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecInt_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecInt_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecInt_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecInt_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecInt

# Register VecInt in _libgeoda:
_libgeoda.VecInt_swigregister(VecInt)

class VecInt64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecInt64_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecInt64___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecInt64___bool__(self)

    def __len__(self):
        return _libgeoda.VecInt64___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecInt64___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecInt64___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecInt64___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecInt64___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecInt64___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecInt64___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecInt64_pop(self)

    def append(self, x):
        return _libgeoda.VecInt64_append(self, x)

    def empty(self):
        return _libgeoda.VecInt64_empty(self)

    def size(self):
        return _libgeoda.VecInt64_size(self)

    def swap(self, v):
        return _libgeoda.VecInt64_swap(self, v)

    def begin(self):
        return _libgeoda.VecInt64_begin(self)

    def end(self):
        return _libgeoda.VecInt64_end(self)

    def rbegin(self):
        return _libgeoda.VecInt64_rbegin(self)

    def rend(self):
        return _libgeoda.VecInt64_rend(self)

    def clear(self):
        return _libgeoda.VecInt64_clear(self)

    def get_allocator(self):
        return _libgeoda.VecInt64_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecInt64_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecInt64_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecInt64_swiginit(self, _libgeoda.new_VecInt64(*args))

    def push_back(self, x):
        return _libgeoda.VecInt64_push_back(self, x)

    def front(self):
        return _libgeoda.VecInt64_front(self)

    def back(self):
        return _libgeoda.VecInt64_back(self)

    def assign(self, n, x):
        return _libgeoda.VecInt64_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecInt64_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecInt64_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecInt64_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecInt64_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecInt64

# Register VecInt64 in _libgeoda:
_libgeoda.VecInt64_swigregister(VecInt64)

class VecVecInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecVecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecVecInt___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecVecInt___bool__(self)

    def __len__(self):
        return _libgeoda.VecVecInt___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecVecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecVecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecVecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecVecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecVecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecVecInt___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecVecInt_pop(self)

    def append(self, x):
        return _libgeoda.VecVecInt_append(self, x)

    def empty(self):
        return _libgeoda.VecVecInt_empty(self)

    def size(self):
        return _libgeoda.VecVecInt_size(self)

    def swap(self, v):
        return _libgeoda.VecVecInt_swap(self, v)

    def begin(self):
        return _libgeoda.VecVecInt_begin(self)

    def end(self):
        return _libgeoda.VecVecInt_end(self)

    def rbegin(self):
        return _libgeoda.VecVecInt_rbegin(self)

    def rend(self):
        return _libgeoda.VecVecInt_rend(self)

    def clear(self):
        return _libgeoda.VecVecInt_clear(self)

    def get_allocator(self):
        return _libgeoda.VecVecInt_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecVecInt_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecVecInt_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecVecInt_swiginit(self, _libgeoda.new_VecVecInt(*args))

    def push_back(self, x):
        return _libgeoda.VecVecInt_push_back(self, x)

    def front(self):
        return _libgeoda.VecVecInt_front(self)

    def back(self):
        return _libgeoda.VecVecInt_back(self)

    def assign(self, n, x):
        return _libgeoda.VecVecInt_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecVecInt_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecVecInt_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecVecInt_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecVecInt_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecVecInt

# Register VecVecInt in _libgeoda:
_libgeoda.VecVecInt_swigregister(VecVecInt)

class VecUINT8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecUINT8_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecUINT8___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecUINT8___bool__(self)

    def __len__(self):
        return _libgeoda.VecUINT8___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecUINT8___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecUINT8___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecUINT8___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecUINT8___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecUINT8___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecUINT8___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecUINT8_pop(self)

    def append(self, x):
        return _libgeoda.VecUINT8_append(self, x)

    def empty(self):
        return _libgeoda.VecUINT8_empty(self)

    def size(self):
        return _libgeoda.VecUINT8_size(self)

    def swap(self, v):
        return _libgeoda.VecUINT8_swap(self, v)

    def begin(self):
        return _libgeoda.VecUINT8_begin(self)

    def end(self):
        return _libgeoda.VecUINT8_end(self)

    def rbegin(self):
        return _libgeoda.VecUINT8_rbegin(self)

    def rend(self):
        return _libgeoda.VecUINT8_rend(self)

    def clear(self):
        return _libgeoda.VecUINT8_clear(self)

    def get_allocator(self):
        return _libgeoda.VecUINT8_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecUINT8_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecUINT8_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecUINT8_swiginit(self, _libgeoda.new_VecUINT8(*args))

    def push_back(self, x):
        return _libgeoda.VecUINT8_push_back(self, x)

    def front(self):
        return _libgeoda.VecUINT8_front(self)

    def back(self):
        return _libgeoda.VecUINT8_back(self)

    def assign(self, n, x):
        return _libgeoda.VecUINT8_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecUINT8_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecUINT8_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecUINT8_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecUINT8_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecUINT8

# Register VecUINT8 in _libgeoda:
_libgeoda.VecUINT8_swigregister(VecUINT8)

class VecVecUINT8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecVecUINT8_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecVecUINT8___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecVecUINT8___bool__(self)

    def __len__(self):
        return _libgeoda.VecVecUINT8___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecVecUINT8___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecVecUINT8___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecVecUINT8___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecVecUINT8___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecVecUINT8___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecVecUINT8___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecVecUINT8_pop(self)

    def append(self, x):
        return _libgeoda.VecVecUINT8_append(self, x)

    def empty(self):
        return _libgeoda.VecVecUINT8_empty(self)

    def size(self):
        return _libgeoda.VecVecUINT8_size(self)

    def swap(self, v):
        return _libgeoda.VecVecUINT8_swap(self, v)

    def begin(self):
        return _libgeoda.VecVecUINT8_begin(self)

    def end(self):
        return _libgeoda.VecVecUINT8_end(self)

    def rbegin(self):
        return _libgeoda.VecVecUINT8_rbegin(self)

    def rend(self):
        return _libgeoda.VecVecUINT8_rend(self)

    def clear(self):
        return _libgeoda.VecVecUINT8_clear(self)

    def get_allocator(self):
        return _libgeoda.VecVecUINT8_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecVecUINT8_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecVecUINT8_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecVecUINT8_swiginit(self, _libgeoda.new_VecVecUINT8(*args))

    def push_back(self, x):
        return _libgeoda.VecVecUINT8_push_back(self, x)

    def front(self):
        return _libgeoda.VecVecUINT8_front(self)

    def back(self):
        return _libgeoda.VecVecUINT8_back(self)

    def assign(self, n, x):
        return _libgeoda.VecVecUINT8_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecVecUINT8_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecVecUINT8_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecVecUINT8_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecVecUINT8_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecVecUINT8

# Register VecVecUINT8 in _libgeoda:
_libgeoda.VecVecUINT8_swigregister(VecVecUINT8)

class VecVecChar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecVecChar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecVecChar___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecVecChar___bool__(self)

    def __len__(self):
        return _libgeoda.VecVecChar___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecVecChar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecVecChar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecVecChar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecVecChar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecVecChar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecVecChar___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecVecChar_pop(self)

    def append(self, x):
        return _libgeoda.VecVecChar_append(self, x)

    def empty(self):
        return _libgeoda.VecVecChar_empty(self)

    def size(self):
        return _libgeoda.VecVecChar_size(self)

    def swap(self, v):
        return _libgeoda.VecVecChar_swap(self, v)

    def begin(self):
        return _libgeoda.VecVecChar_begin(self)

    def end(self):
        return _libgeoda.VecVecChar_end(self)

    def rbegin(self):
        return _libgeoda.VecVecChar_rbegin(self)

    def rend(self):
        return _libgeoda.VecVecChar_rend(self)

    def clear(self):
        return _libgeoda.VecVecChar_clear(self)

    def get_allocator(self):
        return _libgeoda.VecVecChar_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecVecChar_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecVecChar_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecVecChar_swiginit(self, _libgeoda.new_VecVecChar(*args))

    def push_back(self, x):
        return _libgeoda.VecVecChar_push_back(self, x)

    def front(self):
        return _libgeoda.VecVecChar_front(self)

    def back(self):
        return _libgeoda.VecVecChar_back(self)

    def assign(self, n, x):
        return _libgeoda.VecVecChar_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecVecChar_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecVecChar_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecVecChar_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecVecChar_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecVecChar

# Register VecVecChar in _libgeoda:
_libgeoda.VecVecChar_swigregister(VecVecChar)

class GeoDaWeight(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libgeoda.delete_GeoDaWeight

    def SaveDIDWeights(self, num_obs, newids, stack_ids, ofname):
        return _libgeoda.GeoDaWeight_SaveDIDWeights(self, num_obs, newids, stack_ids, ofname)

    def SaveSpaceTimeWeights(self, ofname, id_vec, time_ids):
        return _libgeoda.GeoDaWeight_SaveSpaceTimeWeights(self, ofname, id_vec, time_ids)

    def CheckNeighbor(self, obs_idx, nbr_idx):
        return _libgeoda.GeoDaWeight_CheckNeighbor(self, obs_idx, nbr_idx)

    def GetNeighbors(self, obs_idx):
        return _libgeoda.GeoDaWeight_GetNeighbors(self, obs_idx)

    def Update(self, undefs):
        return _libgeoda.GeoDaWeight_Update(self, undefs)

    def HasIsolates(self):
        return _libgeoda.GeoDaWeight_HasIsolates(self)

    def GetNbrStats(self):
        return _libgeoda.GeoDaWeight_GetNbrStats(self)

    def GetNbrSize(self, obs_idx):
        return _libgeoda.GeoDaWeight_GetNbrSize(self, obs_idx)

    def SpatialLag(self, obs_idx, data):
        return _libgeoda.GeoDaWeight_SpatialLag(self, obs_idx, data)

    def SaveToFile(self, *args):
        return _libgeoda.GeoDaWeight_SaveToFile(self, *args)

    def GetSparsity(self):
        return _libgeoda.GeoDaWeight_GetSparsity(self)

    def GetDensity(self):
        return _libgeoda.GeoDaWeight_GetDensity(self)

    def GetMinNumNbrs(self):
        return _libgeoda.GeoDaWeight_GetMinNumNbrs(self)

    def GetMaxNumNbrs(self):
        return _libgeoda.GeoDaWeight_GetMaxNumNbrs(self)

    def GetMeanNumNbrs(self):
        return _libgeoda.GeoDaWeight_GetMeanNumNbrs(self)

    def GetMedianNumNbrs(self):
        return _libgeoda.GeoDaWeight_GetMedianNumNbrs(self)

    def GetNumObs(self):
        return _libgeoda.GeoDaWeight_GetNumObs(self)

    def IsInternalUse(self):
        return _libgeoda.GeoDaWeight_IsInternalUse(self)

    def GetTitle(self):
        return _libgeoda.GeoDaWeight_GetTitle(self)

    def GetIDName(self):
        return _libgeoda.GeoDaWeight_GetIDName(self)
    gal_type = _libgeoda.GeoDaWeight_gal_type
    gwt_type = _libgeoda.GeoDaWeight_gwt_type
    weight_type = property(_libgeoda.GeoDaWeight_weight_type_get, _libgeoda.GeoDaWeight_weight_type_set)
    wflnm = property(_libgeoda.GeoDaWeight_wflnm_get, _libgeoda.GeoDaWeight_wflnm_set)
    id_field = property(_libgeoda.GeoDaWeight_id_field_get, _libgeoda.GeoDaWeight_id_field_set)
    title = property(_libgeoda.GeoDaWeight_title_get, _libgeoda.GeoDaWeight_title_set)
    symmetry_checked = property(_libgeoda.GeoDaWeight_symmetry_checked_get, _libgeoda.GeoDaWeight_symmetry_checked_set)
    is_symmetric = property(_libgeoda.GeoDaWeight_is_symmetric_get, _libgeoda.GeoDaWeight_is_symmetric_set)
    num_obs = property(_libgeoda.GeoDaWeight_num_obs_get, _libgeoda.GeoDaWeight_num_obs_set)
    sparsity = property(_libgeoda.GeoDaWeight_sparsity_get, _libgeoda.GeoDaWeight_sparsity_set)
    density = property(_libgeoda.GeoDaWeight_density_get, _libgeoda.GeoDaWeight_density_set)
    min_nbrs = property(_libgeoda.GeoDaWeight_min_nbrs_get, _libgeoda.GeoDaWeight_min_nbrs_set)
    max_nbrs = property(_libgeoda.GeoDaWeight_max_nbrs_get, _libgeoda.GeoDaWeight_max_nbrs_set)
    mean_nbrs = property(_libgeoda.GeoDaWeight_mean_nbrs_get, _libgeoda.GeoDaWeight_mean_nbrs_set)
    median_nbrs = property(_libgeoda.GeoDaWeight_median_nbrs_get, _libgeoda.GeoDaWeight_median_nbrs_set)
    is_internal_use = property(_libgeoda.GeoDaWeight_is_internal_use_get, _libgeoda.GeoDaWeight_is_internal_use_set)

# Register GeoDaWeight in _libgeoda:
_libgeoda.GeoDaWeight_swigregister(GeoDaWeight)

class AbstractLocalSA(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libgeoda.delete_AbstractLocalSA

    def ComputeLoalSA(self):
        return _libgeoda.AbstractLocalSA_ComputeLoalSA(self)

    def CalcPseudoP(self):
        return _libgeoda.AbstractLocalSA_CalcPseudoP(self)

    def CalcPseudoP_threaded(self):
        return _libgeoda.AbstractLocalSA_CalcPseudoP_threaded(self)

    def CalcPseudoP_range(self, obs_start, obs_end, seed_start):
        return _libgeoda.AbstractLocalSA_CalcPseudoP_range(self, obs_start, obs_end, seed_start)

    def LargerPermLocalSA(self, cnt, permNeighbors):
        return _libgeoda.AbstractLocalSA_LargerPermLocalSA(self, cnt, permNeighbors)

    def Run(self):
        return _libgeoda.AbstractLocalSA_Run(self)

    def SetSignificanceFilter(self, filter_id):
        return _libgeoda.AbstractLocalSA_SetSignificanceFilter(self, filter_id)

    def GetSignificanceFilter(self):
        return _libgeoda.AbstractLocalSA_GetSignificanceFilter(self)

    def GetSignificanceCutoff(self):
        return _libgeoda.AbstractLocalSA_GetSignificanceCutoff(self)

    def SetSignificanceCutoff(self, val):
        return _libgeoda.AbstractLocalSA_SetSignificanceCutoff(self, val)

    def GetUserCutoff(self):
        return _libgeoda.AbstractLocalSA_GetUserCutoff(self)

    def SetUserCutoff(self, val):
        return _libgeoda.AbstractLocalSA_SetUserCutoff(self, val)

    def GetBO(self):
        return _libgeoda.AbstractLocalSA_GetBO(self)

    def SetBO(self, val):
        return _libgeoda.AbstractLocalSA_SetBO(self, val)

    def GetFDR(self):
        return _libgeoda.AbstractLocalSA_GetFDR(self)

    def SetFDR(self, val):
        return _libgeoda.AbstractLocalSA_SetFDR(self, val)

    def GetNumPermutations(self):
        return _libgeoda.AbstractLocalSA_GetNumPermutations(self)

    def SetNumPermutations(self, val):
        return _libgeoda.AbstractLocalSA_SetNumPermutations(self, val)

    def GetLastUsedSeed(self):
        return _libgeoda.AbstractLocalSA_GetLastUsedSeed(self)

    def SetLastUsedSeed(self, seed):
        return _libgeoda.AbstractLocalSA_SetLastUsedSeed(self, seed)

    def IsReuseLastSeed(self):
        return _libgeoda.AbstractLocalSA_IsReuseLastSeed(self)

    def SetReuseLastSeed(self, reuse):
        return _libgeoda.AbstractLocalSA_SetReuseLastSeed(self, reuse)

    def GetHasIsolates(self):
        return _libgeoda.AbstractLocalSA_GetHasIsolates(self)

    def GetHasUndefined(self):
        return _libgeoda.AbstractLocalSA_GetHasUndefined(self)

    def GetDefaultCategories(self):
        return _libgeoda.AbstractLocalSA_GetDefaultCategories(self)

    def GetDefaultCutoffs(self):
        return _libgeoda.AbstractLocalSA_GetDefaultCutoffs(self)

    def GetLocalSignificanceValues(self):
        return _libgeoda.AbstractLocalSA_GetLocalSignificanceValues(self)

    def GetClusterIndicators(self):
        return _libgeoda.AbstractLocalSA_GetClusterIndicators(self)

    def GetSigCatIndicators(self):
        return _libgeoda.AbstractLocalSA_GetSigCatIndicators(self)

    def IsRowStandardize(self):
        return _libgeoda.AbstractLocalSA_IsRowStandardize(self)

    def SetRowStandardize(self, rowStandardize):
        return _libgeoda.AbstractLocalSA_SetRowStandardize(self, rowStandardize)

    def GetNumThreads(self):
        return _libgeoda.AbstractLocalSA_GetNumThreads(self)

    def SetNumThreads(self, n_threads):
        return _libgeoda.AbstractLocalSA_SetNumThreads(self, n_threads)

# Register AbstractLocalSA in _libgeoda:
_libgeoda.AbstractLocalSA_swigregister(AbstractLocalSA)

class UniLisa(AbstractLocalSA):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, num_obs, data, undefs, w):
        _libgeoda.UniLisa_swiginit(self, _libgeoda.new_UniLisa(num_obs, data, undefs, w))
    __swig_destroy__ = _libgeoda.delete_UniLisa

    def ComputeLoalSA(self):
        return _libgeoda.UniLisa_ComputeLoalSA(self)

    def LargerPermLocalSA(self, cnt, permNeighbors):
        return _libgeoda.UniLisa_LargerPermLocalSA(self, cnt, permNeighbors)

    def GetClusterIndicators(self):
        return _libgeoda.UniLisa_GetClusterIndicators(self)

    def GetLagValues(self):
        return _libgeoda.UniLisa_GetLagValues(self)

    def GetLocalMoranValues(self):
        return _libgeoda.UniLisa_GetLocalMoranValues(self)

# Register UniLisa in _libgeoda:
_libgeoda.UniLisa_swigregister(UniLisa)

class GeoDaColumn(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    integer_type = _libgeoda.GeoDaColumn_integer_type
    string_type = _libgeoda.GeoDaColumn_string_type
    real_type = _libgeoda.GeoDaColumn_real_type
    name = property(_libgeoda.GeoDaColumn_name_get, _libgeoda.GeoDaColumn_name_set)
    field_type = property(_libgeoda.GeoDaColumn_field_type_get, _libgeoda.GeoDaColumn_field_type_set)
    field_length = property(_libgeoda.GeoDaColumn_field_length_get, _libgeoda.GeoDaColumn_field_length_set)
    field_decimals = property(_libgeoda.GeoDaColumn_field_decimals_get, _libgeoda.GeoDaColumn_field_decimals_set)

    def __init__(self, nm, ft, flen, fdec):
        _libgeoda.GeoDaColumn_swiginit(self, _libgeoda.new_GeoDaColumn(nm, ft, flen, fdec))
    __swig_destroy__ = _libgeoda.delete_GeoDaColumn

# Register GeoDaColumn in _libgeoda:
_libgeoda.GeoDaColumn_swigregister(GeoDaColumn)

class GeoDaIntColumn(GeoDaColumn):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    data = property(_libgeoda.GeoDaIntColumn_data_get, _libgeoda.GeoDaIntColumn_data_set)

    def GetData(self):
        return _libgeoda.GeoDaIntColumn_GetData(self)

    def SetData(self, vals):
        return _libgeoda.GeoDaIntColumn_SetData(self, vals)

    def __init__(self, nm, vals):
        _libgeoda.GeoDaIntColumn_swiginit(self, _libgeoda.new_GeoDaIntColumn(nm, vals))
    __swig_destroy__ = _libgeoda.delete_GeoDaIntColumn

# Register GeoDaIntColumn in _libgeoda:
_libgeoda.GeoDaIntColumn_swigregister(GeoDaIntColumn)

class GeoDaStringColumn(GeoDaColumn):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    data = property(_libgeoda.GeoDaStringColumn_data_get, _libgeoda.GeoDaStringColumn_data_set)

    def GetData(self):
        return _libgeoda.GeoDaStringColumn_GetData(self)

    def SetData(self, vals):
        return _libgeoda.GeoDaStringColumn_SetData(self, vals)

    def __init__(self, nm, vals):
        _libgeoda.GeoDaStringColumn_swiginit(self, _libgeoda.new_GeoDaStringColumn(nm, vals))
    __swig_destroy__ = _libgeoda.delete_GeoDaStringColumn

# Register GeoDaStringColumn in _libgeoda:
_libgeoda.GeoDaStringColumn_swigregister(GeoDaStringColumn)

class GeoDaRealColumn(GeoDaColumn):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    data = property(_libgeoda.GeoDaRealColumn_data_get, _libgeoda.GeoDaRealColumn_data_set)

    def GetData(self):
        return _libgeoda.GeoDaRealColumn_GetData(self)

    def SetData(self, vals):
        return _libgeoda.GeoDaRealColumn_SetData(self, vals)

    def __init__(self, nm, vals):
        _libgeoda.GeoDaRealColumn_swiginit(self, _libgeoda.new_GeoDaRealColumn(nm, vals))
    __swig_destroy__ = _libgeoda.delete_GeoDaRealColumn

# Register GeoDaRealColumn in _libgeoda:
_libgeoda.GeoDaRealColumn_swigregister(GeoDaRealColumn)

class GeoDaTable(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _libgeoda.GeoDaTable_swiginit(self, _libgeoda.new_GeoDaTable())
    __swig_destroy__ = _libgeoda.delete_GeoDaTable

    def AddIntColumn(self, nm, vals):
        return _libgeoda.GeoDaTable_AddIntColumn(self, nm, vals)

    def AddStringColumn(self, nm, vals):
        return _libgeoda.GeoDaTable_AddStringColumn(self, nm, vals)

    def AddRealColumn(self, nm, vals):
        return _libgeoda.GeoDaTable_AddRealColumn(self, nm, vals)

    def GetColumn(self, *args):
        return _libgeoda.GeoDaTable_GetColumn(self, *args)

    def GetNumCols(self):
        return _libgeoda.GeoDaTable_GetNumCols(self)

# Register GeoDaTable in _libgeoda:
_libgeoda.GeoDaTable_swigregister(GeoDaTable)

class GeoDa(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    point_type = _libgeoda.GeoDa_point_type
    polygon_type = _libgeoda.GeoDa_polygon_type
    line_type = _libgeoda.GeoDa_line_type

    def __init__(self, *args):
        _libgeoda.GeoDa_swiginit(self, _libgeoda.new_GeoDa(*args))
    __swig_destroy__ = _libgeoda.delete_GeoDa

    def GetMapType(self):
        return _libgeoda.GeoDa_GetMapType(self)

    def GetNumObs(self):
        return _libgeoda.GeoDa_GetNumObs(self)

    def GetNumCols(self):
        return _libgeoda.GeoDa_GetNumCols(self)

    def GetFieldTypes(self):
        return _libgeoda.GeoDa_GetFieldTypes(self)

    def GetFieldNames(self):
        return _libgeoda.GeoDa_GetFieldNames(self)

    def GetGeometryWKB(self):
        return _libgeoda.GeoDa_GetGeometryWKB(self)

    def GetGeometryWKT(self):
        return _libgeoda.GeoDa_GetGeometryWKT(self)

    def GetNumericCol(self, col_name):
        return _libgeoda.GeoDa_GetNumericCol(self, col_name)

    def GetIntegerCol(self, col_name):
        return _libgeoda.GeoDa_GetIntegerCol(self, col_name)

    def GetStringCol(self, col_name):
        return _libgeoda.GeoDa_GetStringCol(self, col_name)

    def GetUndefinesCol(self, col_name):
        return _libgeoda.GeoDa_GetUndefinesCol(self, col_name)

    def GetName(self):
        return _libgeoda.GeoDa_GetName(self)

    def CreateContiguityWeights(self, *args):
        return _libgeoda.GeoDa_CreateContiguityWeights(self, *args)

    def CreateDistanceWeights(self, dist_thres, power=1.0, is_inverse=False):
        return _libgeoda.GeoDa_CreateDistanceWeights(self, dist_thres, power, is_inverse)

    def LISA(self, *args):
        return _libgeoda.GeoDa_LISA(self, *args)

    def SKATER(self, *args):
        return _libgeoda.GeoDa_SKATER(self, *args)

# Register GeoDa in _libgeoda:
_libgeoda.GeoDa_swigregister(GeoDa)


def test():
    return _libgeoda.test()

def ToGeoDaColumn(*args):
    return _libgeoda.ToGeoDaColumn(*args)
class VecGeoDaColumn(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _libgeoda.VecGeoDaColumn_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libgeoda.VecGeoDaColumn___nonzero__(self)

    def __bool__(self):
        return _libgeoda.VecGeoDaColumn___bool__(self)

    def __len__(self):
        return _libgeoda.VecGeoDaColumn___len__(self)

    def __getslice__(self, i, j):
        return _libgeoda.VecGeoDaColumn___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libgeoda.VecGeoDaColumn___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libgeoda.VecGeoDaColumn___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libgeoda.VecGeoDaColumn___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libgeoda.VecGeoDaColumn___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libgeoda.VecGeoDaColumn___setitem__(self, *args)

    def pop(self):
        return _libgeoda.VecGeoDaColumn_pop(self)

    def append(self, x):
        return _libgeoda.VecGeoDaColumn_append(self, x)

    def empty(self):
        return _libgeoda.VecGeoDaColumn_empty(self)

    def size(self):
        return _libgeoda.VecGeoDaColumn_size(self)

    def swap(self, v):
        return _libgeoda.VecGeoDaColumn_swap(self, v)

    def begin(self):
        return _libgeoda.VecGeoDaColumn_begin(self)

    def end(self):
        return _libgeoda.VecGeoDaColumn_end(self)

    def rbegin(self):
        return _libgeoda.VecGeoDaColumn_rbegin(self)

    def rend(self):
        return _libgeoda.VecGeoDaColumn_rend(self)

    def clear(self):
        return _libgeoda.VecGeoDaColumn_clear(self)

    def get_allocator(self):
        return _libgeoda.VecGeoDaColumn_get_allocator(self)

    def pop_back(self):
        return _libgeoda.VecGeoDaColumn_pop_back(self)

    def erase(self, *args):
        return _libgeoda.VecGeoDaColumn_erase(self, *args)

    def __init__(self, *args):
        _libgeoda.VecGeoDaColumn_swiginit(self, _libgeoda.new_VecGeoDaColumn(*args))

    def push_back(self, x):
        return _libgeoda.VecGeoDaColumn_push_back(self, x)

    def front(self):
        return _libgeoda.VecGeoDaColumn_front(self)

    def back(self):
        return _libgeoda.VecGeoDaColumn_back(self)

    def assign(self, n, x):
        return _libgeoda.VecGeoDaColumn_assign(self, n, x)

    def resize(self, *args):
        return _libgeoda.VecGeoDaColumn_resize(self, *args)

    def insert(self, *args):
        return _libgeoda.VecGeoDaColumn_insert(self, *args)

    def reserve(self, n):
        return _libgeoda.VecGeoDaColumn_reserve(self, n)

    def capacity(self):
        return _libgeoda.VecGeoDaColumn_capacity(self)
    __swig_destroy__ = _libgeoda.delete_VecGeoDaColumn

# Register VecGeoDaColumn in _libgeoda:
_libgeoda.VecGeoDaColumn_swigregister(VecGeoDaColumn)



