# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r -outcurrentdir -o geoda_proxy_wrap.cpp ../geoda_proxy.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_GeoDaProxy', contains = 'C++Reference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of new_GeoDaProxy

`GeoDaProxy__SWIG_0` = function()
{
  ;ans = .Call('R_swig_new_GeoDaProxy__SWIG_0', PACKAGE='geoda');
  ans <- if (is.null(ans)) ans
  else new("_p_GeoDaProxy", ref=ans);
  
  reg.finalizer(ans@ref, delete_GeoDaProxy)
  ans
  
}

attr(`GeoDaProxy__SWIG_0`, 'returnType') = '_p_GeoDaProxy'
class(`GeoDaProxy__SWIG_0`) = c("SWIGFunction", class('GeoDaProxy__SWIG_0'))

# Start of new_GeoDaProxy

`GeoDaProxy__SWIG_1` = function(pDsPath)
{
  pDsPath = as(pDsPath, "character"); 
  ;ans = .Call('R_swig_new_GeoDaProxy__SWIG_1', pDsPath, PACKAGE='geoda');
  ans <- if (is.null(ans)) ans
  else new("_p_GeoDaProxy", ref=ans);
  
  reg.finalizer(ans@ref, delete_GeoDaProxy)
  ans
  
}

attr(`GeoDaProxy__SWIG_1`, 'returnType') = '_p_GeoDaProxy'
attr(`GeoDaProxy__SWIG_1`, "inputTypes") = c('character')
class(`GeoDaProxy__SWIG_1`) = c("SWIGFunction", class('GeoDaProxy__SWIG_1'))

`GeoDaProxy` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
# dispatch functions 2
  if (argc == 0) {
    f <- GeoDaProxy__SWIG_0; 
  } else if (argc == 1) {
    if (is.character(argv[[1]])) {
      f <- GeoDaProxy__SWIG_1; 
    }
  } else {
    stop("cannot find overloaded function for GeoDaProxy with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of delete_GeoDaProxy

`delete_GeoDaProxy` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_GeoDaProxy', self, PACKAGE='geoda');
  
}

attr(`delete_GeoDaProxy`, 'returnType') = 'void'
attr(`delete_GeoDaProxy`, "inputTypes") = c('_p_GeoDaProxy')
class(`delete_GeoDaProxy`) = c("SWIGFunction", class('delete_GeoDaProxy'))

# Start of GeoDaProxy_GetValues

`GeoDaProxy_GetValues` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_GeoDaProxy_GetValues', self, as.logical(.copy), PACKAGE='geoda');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_double_t", ref=ans);
  
  ans
  
}

attr(`GeoDaProxy_GetValues`, 'returnType') = '_p_std__vectorT_double_t'
attr(`GeoDaProxy_GetValues`, "inputTypes") = c('_p_GeoDaProxy')
class(`GeoDaProxy_GetValues`) = c("SWIGFunction", class('GeoDaProxy_GetValues'))

# Start of GeoDaProxy_GetName

`GeoDaProxy_GetName` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_GeoDaProxy_GetName', self, as.logical(.copy), PACKAGE='geoda');
  
}

attr(`GeoDaProxy_GetName`, 'returnType') = 'character'
attr(`GeoDaProxy_GetName`, "inputTypes") = c('_p_GeoDaProxy')
class(`GeoDaProxy_GetName`) = c("SWIGFunction", class('GeoDaProxy_GetName'))

# Start of accessor method for GeoDaProxy
setMethod('$', '_p_GeoDaProxy', function(x, name)

{
  accessorFuns = list('GetValues' = GeoDaProxy_GetValues, 'GetName' = GeoDaProxy_GetName);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for GeoDaProxy
setMethod('delete', '_p_GeoDaProxy', function(obj) {delete_GeoDaProxy(obj)})


